In [4]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
data = "data/"
train = pd.read_csv(data + "mnist_train.csv")
test = pd.read_csv(data + "mnist_test.csv")

In [3]:
train.head()

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
test.head()

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Data shape: 60000 images, 784 pixel per image (60000, 784)
Convetion for Neural Network: column = Training item (e.g. 7), row = features
Reshape to (784, 60000)

In [5]:
train = np.array(train)
test = np.array(test)

X_train = train[:, 1:].T / 255.0
Y_train = train[:, 0].reshape(1, -1)

X_test = test[:, 1:].T / 255.0
Y_test = test[:, 0].reshape(1, -1)

print(X_train.shape)  # (784, 60000)
print(Y_train.shape)  # (1, 60000)

(784, 60000)
(1, 60000)

Input Layer: 784 Inputs
Hidden Layer: 128 Neurons
Output Layer: 10 Output-Neurons

Initilaize random Weights and Bias using He-Initilaization (N(0.2/n_in)

In [6]:
def init_params():
    W1 = np.random.randn(128,784)*0.01
    b1 = np.zeros((128,1))
    W2 = np.random.randn(128,784)*0.01
    b2 = np.zeros((10,1))
    return W1,b1,W2,b2

ReLU Activation for Hidden-Neurons: max(v,0)

In [7]:
def ReLU(z): return max(z,0)

Softmax for Output-Layer: exp(v) / sum exp(v)

In [8]:
def softmax(z): return np.exp(z)/ np.sum(np.exp(z))

Forward propagation:
Hidden-Layer Input: Z1 = W1*X+b1
Hidden-Layer Activation: A1 = ReLU(Z1)
Output-Layer Input: Z2 = W2*A1 + b2
Output-Layer Activation: A2 = Softmax(Z2)

In [ ]:
def forward(W1,W2,b1,b2):
    Z1 = W1 @ X_train + b1
    A1 = ReLU(Z1)
    Z2 = W2 @ A1 + b2
    A2 = softmax(Z2)

    return Z1, A1, Z2, A2

In [ ]:
def one_hot(Y):
    one_hot_Y =np.zeros((Y.size, Y.max()+1))
    one_hot_Y[np.arange(Y.size),Y] = 1
    return one_hot_Y.T

Back propagation:

In [ ]:
def backward(Z1, A1, Z2, A2):